# Media Mix Modeling: How to Measure the Effectiveness of Advertising with Python & LightweightMMM

Resources:

https://towardsdatascience.com/media-mix-modeling-how-to-measure-the-effectiveness-of-advertising-with-python-lightweightmmm-b6d7de110ae6
https://github.com/takechanman1228/mmm_pydata_global_2022/blob/main/simple_end_to_end_demo_pydataglobal.ipynb

In [15]:
import pandas as pd

df = pd.read_csv('data.csv')

df.head()

,Unnamed: 0,wk_strt_dt,yr_nbr,qtr_nbr,prd,wk_nbr,wk_in_yr_nbr,mdip_dm,mdip_inst,mdip_nsp,...,seas_prd_12,seas_week_40,seas_week_41,seas_week_42,seas_week_43,seas_week_44,seas_week_45,seas_week_46,seas_week_47,seas_week_48
0,0,2014-08-03,2014,3,7,1,27,4863885,29087520,2421933,...,0,0,0,0,0,0,0,0,0,0
1,1,2014-08-10,2014,3,7,2,28,20887502,8345120,3984494,...,0,0,0,0,0,0,0,0,0,0
2,2,2014-08-17,2014,3,7,3,29,11097724,17276800,1846832,...,0,0,0,0,0,0,0,0,0,0
3,3,2014-08-24,2014,3,7,4,30,1023446,18468480,2394834,...,0,0,0,0,0,0,0,0,0,0
4,4,2014-08-31,2014,3,8,1,31,21109811,26659920,3312008,...,0,0,0,0,0,0,0,0,0,0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 81 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                209 non-null    int64
 1   wk_strt_dt                209 non-null    object
 2   yr_nbr                    209 non-null    int64
 3   qtr_nbr                   209 non-null    int64
 4   prd                       209 non-null    int64
 5   wk_nbr                    209 non-null    int64
 6   wk_in_yr_nbr              209 non-null    int64
 7   mdip_dm                   209 non-null    int64
 8   mdip_inst                 209 non-null    int64
 9   mdip_nsp                  209 non-null    int64
 10  mdip_auddig               209 non-null    int64
 11  mdip_audtr                209 non-null    int64
 12  mdip_vidtr                209 non-null    int64
 13  mdip_viddig               209 non-null    int64
 14  mdip_so                   209 non-null    int64
 15  mdip_on                   209 non-null    int64
 16  mdip_em                   209 non-null    int64
 17  mdip_sms                  209 non-null    int64
 18  mdip_aff                  209 non-null    int64
 19  mdip_sem                  209 non-null    int64
 20  mdsp_dm                   209 non-null    float64
 21  mdsp_inst                 209 non-null    float64
 22  mdsp_nsp                  209 non-null    float64
 23  mdsp_auddig               209 non-null    float64
 24  mdsp_audtr                209 non-null    float64
 25  mdsp_vidtr                209 non-null    float64
 26  mdsp_viddig               209 non-null    float64
 27  mdsp_so                   209 non-null    float64
 28  mdsp_on                   209 non-null    float64
 29  mdsp_sem                  209 non-null    float64
 30  sales                     209 non-null    float64
 31  me_ics_all                209 non-null    float64
 32  me_gas_dpg                209 non-null    float64
 33  st_ct                     209 non-null    float64
 34  mrkdn_valadd_edw          209 non-null    float64
 35  mrkdn_pdm                 209 non-null    float64
 36  va_pub_0.15               209 non-null    int64
 37  va_pub_0.2                209 non-null    int64
 38  va_pub_0.25               209 non-null    int64
 39  va_pub_0.3                209 non-null    int64
 40  hldy_Black Friday         209 non-null    int64
 41  hldy_Christmas Day        209 non-null    int64
 42  hldy_Christmas Eve        209 non-null    int64
 43  hldy_Columbus Day         209 non-null    int64
 44  hldy_Cyber Monday         209 non-null    int64
 45  hldy_Day after Christmas  209 non-null    int64
 46  hldy_Easter               209 non-null    int64
 47  hldy_Father's Day         209 non-null    int64
 48  hldy_Green Monday         209 non-null    int64
 49  hldy_July 4th             209 non-null    int64
 50  hldy_Labor Day            209 non-null    int64
 51  hldy_MLK                  209 non-null    int64
 52  hldy_Memorial Day         209 non-null    int64
 53  hldy_Mother's Day         209 non-null    int64
 54  hldy_NYE                  209 non-null    int64
 55  hldy_New Year's Day       209 non-null    int64
 56  hldy_Pre Thanksgiving     209 non-null    int64
 57  hldy_Presidents Day       209 non-null    int64
 58  hldy_Prime Day            209 non-null    int64
 59  hldy_Thanksgiving         209 non-null    int64
 60  hldy_Valentine's Day      209 non-null    int64
 61  hldy_Veterans Day         209 non-null    int64
 62  seas_prd_1                209 non-null    int64
 63  seas_prd_2                209 non-null    int64
 64  seas_prd_3                209 non-null    int64
 65  seas_prd_4                209 non-null    int64
 66  seas_prd_5                209 non-null    int64
 67  seas_prd_6                209 non-null    int64
 68  seas_prd_7                209 non-null    int64
 69  seas_prd_8                209 non-null    int64
 70  seas_prd_9                209 non-null    int64
 71  seas_prd_12               209 non-null    int64
 72  seas_week_40              209 non-null    int64
 73  seas_week_41              209 non-null    int64
 74  seas_week_42              209 non-null    int64
 75  seas_week_43              209 non-null    int64
 76  seas_week_44              209 non-null    int64
 77  seas_week_45              209 non-null    int64
 78  seas_week_46              209 non-null    int64
 79  seas_week_47              209 non-null    int64
 80  seas_week_48              209 non-null    int64
dtypes: float64(16), int64(64), object(1)
memory usage: 132.4+ KB

In [17]:
# 1. media variables
# media spending (Simplified media channel for demo)
mdsp_cols=[col for col in df.columns if 'mdsp_' in col and col !='mdsp_viddig' and col != 'mdsp_auddig' and col != 'mdsp_sem']

# 2. control variables
# holiday variables
hldy_cols = [col for col in df.columns if 'hldy_' in col]
# seasonality variables
seas_cols = [col for col in df.columns if 'seas_' in col]

control_vars =  hldy_cols + seas_cols

# 3. sales variables
sales_cols =['sales']

df_main = df[['wk_strt_dt']+sales_cols+mdsp_cols+control_vars]
df_main = df_main.rename(columns={'mdsp_dm': 'Direct Mail', 'mdsp_inst': 'Insert', 'mdsp_nsp': 'Newspaper', 'mdsp_audtr': 'Radio', 'mdsp_vidtr': 'TV', 'mdsp_so': 'Social Media', 'mdsp_on': 'Online Display'})

In [18]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   wk_strt_dt                209 non-null    object
 1   sales                     209 non-null    float64
 2   Direct Mail               209 non-null    float64
 3   Insert                    209 non-null    float64
 4   Newspaper                 209 non-null    float64
 5   Radio                     209 non-null    float64
 6   TV                        209 non-null    float64
 7   Social Media              209 non-null    float64
 8   Online Display            209 non-null    float64
 9   hldy_Black Friday         209 non-null    int64
 10  hldy_Christmas Day        209 non-null    int64
 11  hldy_Christmas Eve        209 non-null    int64
 12  hldy_Columbus Day         209 non-null    int64
 13  hldy_Cyber Monday         209 non-null    int64
 14  hldy_Day after Christmas  209 non-null    int64
 15  hldy_Easter               209 non-null    int64
 16  hldy_Father's Day         209 non-null    int64
 17  hldy_Green Monday         209 non-null    int64
 18  hldy_July 4th             209 non-null    int64
 19  hldy_Labor Day            209 non-null    int64
 20  hldy_MLK                  209 non-null    int64
 21  hldy_Memorial Day         209 non-null    int64
 22  hldy_Mother's Day         209 non-null    int64
 23  hldy_NYE                  209 non-null    int64
 24  hldy_New Year's Day       209 non-null    int64
 25  hldy_Pre Thanksgiving     209 non-null    int64
 26  hldy_Presidents Day       209 non-null    int64
 27  hldy_Prime Day            209 non-null    int64
 28  hldy_Thanksgiving         209 non-null    int64
 29  hldy_Valentine's Day      209 non-null    int64
 30  hldy_Veterans Day         209 non-null    int64
 31  seas_prd_1                209 non-null    int64
 32  seas_prd_2                209 non-null    int64
 33  seas_prd_3                209 non-null    int64
 34  seas_prd_4                209 non-null    int64
 35  seas_prd_5                209 non-null    int64
 36  seas_prd_6                209 non-null    int64
 37  seas_prd_7                209 non-null    int64
 38  seas_prd_8                209 non-null    int64
 39  seas_prd_9                209 non-null    int64
 40  seas_prd_12               209 non-null    int64
 41  seas_week_40              209 non-null    int64
 42  seas_week_41              209 non-null    int64
 43  seas_week_42              209 non-null    int64
 44  seas_week_43              209 non-null    int64
 45  seas_week_44              209 non-null    int64
 46  seas_week_45              209 non-null    int64
 47  seas_week_46              209 non-null    int64
 48  seas_week_47              209 non-null    int64
 49  seas_week_48              209 non-null    int64
dtypes: float64(8), int64(41), object(1)
memory usage: 81.8+ KB

In [19]:
SEED = 105
data_size = len(df_main)

n_media_channels = len(mdsp_cols)
n_extra_features = len(control_vars)
media_data = df_main[mdsp_cols].to_numpy()
extra_features = df_main[control_vars].to_numpy()
target = df_main['sales'].to_numpy()
costs = df_main[mdsp_cols].sum().to_numpy()

# Split and scale data.
test_data_period_size = 24
split_point = data_size - test_data_period_size
# Media data
media_data_train = media_data[:split_point, ...]
media_data_test = media_data[split_point:, ...]
# Extra features
extra_features_train = extra_features[:split_point, ...]
extra_features_test = extra_features[split_point:, ...]
# Target
target_train = target[:split_point]

KeyError: "None of [Index(['mdsp_dm', 'mdsp_inst', 'mdsp_nsp', 'mdsp_audtr', 'mdsp_vidtr',\n       'mdsp_so', 'mdsp_on'],\n      dtype='object')] are in the [columns]"